language: node_js

node_js:
  - "12"

install:
  - "npm install"

sudo: required # https://github.com/travis-ci/travis-ci/issues/8836

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success: 'npm run coveralls'